{
 "title": "FastAPI metrics",
 "description": "FastAPI metrics",
 "tags": [ "API" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum(irate(http_request_duration_highr_seconds_bucket{le=\"0.1\"}[1m]))\n+\n(\nsum(irate(http_request_duration_highr_seconds_bucket{le=\"0.25\"}[1m])) - sum(irate(http_request_duration_highr_seconds_bucket{le=\"0.1\"}[1m]))\n) / 2\n)\n/\nsum(irate(http_request_duration_highr_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "CPU seconds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total[1m]))"
    }
   ]
  },
  {
   "title": "Virual Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_virtual_memory_bytes{job=\"fastapi\"})"
    }
   ]
  },
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(http_requests_total[1m]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum (irate(http_requests_total{status=~\"^5..$\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (irate(http_requests_total{status=~\"^4..$\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (irate(http_requests_total{status=~\"^2..$\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    }
   ]
  },
  {
   "title": "Request rate by Method (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (irate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Apdex Score: target 100ms, tolerated: 250ms",
   "type": "graph",
   "description": "Apdex score: (Satisfied + Tolerating / 2) / Total samples",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\nsum(irate(http_request_duration_highr_seconds_bucket{le=\"0.1\"}[1m]))\n+\n(\nsum(irate(http_request_duration_highr_seconds_bucket{le=\"0.25\"}[1m])) - sum(irate(http_request_duration_highr_seconds_bucket{le=\"0.1\"}[1m]))\n) / 2\n)\n/\nsum(irate(http_request_duration_highr_seconds_count[1m]))",
     "legendFormat": "Apdex Score"
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( sum(irate(http_request_duration_highr_seconds_bucket{le=\"0.01\"}[1m])) /  sum(irate(http_request_duration_highr_seconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 10ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_highr_seconds_bucket{le=\"0.1\"}[1m])) /  sum(irate(http_request_duration_highr_seconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 100ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_highr_seconds_bucket{le=\"0.25\"}[1m])) /  sum(irate(http_request_duration_highr_seconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 250ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_highr_seconds_bucket{le=\"0.5\"}[1m])) /  sum(irate(http_request_duration_highr_seconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 500ms (%)"
    }
   ]
  },
  {
   "title": "Top 3 API calls (by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(irate(http_requests_total{handler!=\"none\"}[1m])) by (handler))"
    }
   ]
  },
  {
   "title": "Top 3 API Error Calls ( 5XX, by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(irate(http_requests_total{status=~\"^5..$\", handler!=\"none\"}[1m])) by (handler))"
    }
   ]
  }
 ]
}